/* START QUERY BUILDER */
DEFINE
    MPARAMETER 'CapacityID' ="40EF7A5E-1383-4947-A015-D6C46AFB919B"
    --11CE1374-106A-4A28-A165-8A164EEFCC18 - old - 40EF7A5E-1383-4947-A015-D6C46AFB919B - new--
EVALUATE
SUMMARIZECOLUMNS(
    Dates[Date],
    "Avg utilization %", [Avg utilization %],
    "Peak utilization %", [Peak utilization %],
    "Dynamic M1 throttling (min)", [Dynamic M1 throttling (min)]
)
ORDER BY 
    Dates[Date] ASC
/* END QUERY BUILDER */