let
    // Define the personal access token
    token = #"Acess Token",
    
    // Define the headers with the personal access token
    headers = [
        #"Authorization" = "Bearer " & token,
        #"Accept" = "application/json"
    ],
    
    // Function to fetch all pages
    GetAllPages = (url as text) as list =>
        let
            GetPage = (startAt as number) as record =>
                let
                    pageUrl = url & "&startAt=" & Text.From(startAt) & "&maxResults=100",
                    options = [Headers = headers],
                    response = Json.Document(Web.Contents(pageUrl, options))
                in
                    response,
            
            // Get first page to determine total records
            firstPage = GetPage(0),
            totalRecords = firstPage[total],
            maxResults = 100,
            
            // Calculate number of pages needed
            pageCount = Number.RoundUp(totalRecords / maxResults),
            
            // Generate list of page numbers
            pageIndices = List.Transform({0..pageCount-1}, each _ * maxResults),
            
            // Fetch all pages
            allPages = List.Transform(pageIndices, each GetPage(_)),
            
            // Combine all issues from all pages
            allIssues = List.Combine(List.Transform(allPages, each _[issues]))
        in
            allIssues,
    
    // Get all issues using pagination
    AllIssues = GetAllPages(URL),
    
    // Convert to table
    #"Converted to Table" = Table.FromList(AllIssues, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"expand", "id", "self", "key", "fields"}, {"issues.expand", "issues.id", "issues.self", "issues.key", "issues.fields"}),
    
   #"Expanded issues.fields.parent" = Table.ExpandRecordColumn(#"Expanded issues.fields", "issues.fields.parent", {"id", "key", "self", "fields"}, {"issues.fields.parent.id", "issues.fields.parent.key", "issues.fields.parent.self", "issues.fields.parent.fields"}),
    #"Expanded issues.fields.parent.fields" = Table.ExpandRecordColumn(#"Expanded issues.fields.parent", "issues.fields.parent.fields", {"summary", "status", "priority", "issuetype"}, {"issues.fields.parent.fields.summary", "issues.fields.parent.fields.status", "issues.fields.parent.fields.priority", "issues.fields.parent.fields.issuetype"}),
    #"Expanded issues.fields.parent.fields.status" = Table.ExpandRecordColumn(#"Expanded issues.fields.parent.fields", "issues.fields.parent.fields.status", {"self", "description", "iconUrl", "name", "id", "statusCategory"}, {"issues.fields.parent.fields.status.self", "issues.fields.parent.fields.status.description", "issues.fields.parent.fields.status.iconUrl", "issues.fields.parent.fields.status.name", "issues.fields.parent.fields.status.id", "issues.fields.parent.fields.status.statusCategory"}),
    #"Expanded issues.fields.parent.fields.status.statusCategory" = Table.ExpandRecordColumn(#"Expanded issues.fields.parent.fields.status", "issues.fields.parent.fields.status.statusCategory", {"self", "id", "key", "colorName", "name"}, {"issues.fields.parent.fields.status.statusCategory.self", "issues.fields.parent.fields.status.statusCategory.id", "issues.fields.parent.fields.status.statusCategory.key", "issues.fields.parent.fields.status.statusCategory.colorName", "issues.fields.parent.fields.status.statusCategory.name"}),
    #"Expanded issues.fields.parent.fields.priority" = Table.ExpandRecordColumn(#"Expanded issues.fields.parent.fields.status.statusCategory", "issues.fields.parent.fields.priority", {"self", "iconUrl", "name", "id"}, {"issues.fields.parent.fields.priority.self", "issues.fields.parent.fields.priority.iconUrl", "issues.fields.parent.fields.priority.name", "issues.fields.parent.fields.priority.id"}),
    #"Expanded issues.fields.parent.fields.issuetype" = Table.ExpandRecordColumn(#"Expanded issues.fields.parent.fields.priority", "issues.fields.parent.fields.issuetype", {"self", "id", "description", "iconUrl", "name", "subtask", "avatarId"}, {"issues.fields.parent.fields.issuetype.self", "issues.fields.parent.fields.issuetype.id", "issues.fields.parent.fields.issuetype.description", "issues.fields.parent.fields.issuetype.iconUrl", "issues.fields.parent.fields.issuetype.name", "issues.fields.parent.fields.issuetype.subtask", "issues.fields.parent.fields.issuetype.avatarId"}),
    #"Expanded issues.fields.customfield_27190" = Table.ExpandRecordColumn(#"Expanded issues.fields.parent.fields.issuetype", "issues.fields.customfield_27190", {"self", "value", "id", "disabled"}, {"issues.fields.customfield_27190.self", "issues.fields.customfield_27190.value", "issues.fields.customfield_27190.id", "issues.fields.customfield_27190.disabled"}),
    #"Expanded issues.fields.assignee" = Table.ExpandRecordColumn(#"Expanded issues.fields.customfield_27190", "issues.fields.assignee", {"self", "name", "key", "emailAddress", "avatarUrls", "displayName", "active", "timeZone"}, {"issues.fields.assignee.self", "issues.fields.assignee.name", "issues.fields.assignee.key", "issues.fields.assignee.emailAddress", "issues.fields.assignee.avatarUrls", "issues.fields.assignee.displayName", "issues.fields.assignee.active", "issues.fields.assignee.timeZone"}),
    #"Expanded issues.fields.assignee.avatarUrls" = Table.ExpandRecordColumn(#"Expanded issues.fields.assignee", "issues.fields.assignee.avatarUrls", {"48x48", "24x24", "16x16", "32x32"}, {"issues.fields.assignee.avatarUrls.48x48", "issues.fields.assignee.avatarUrls.24x24", "issues.fields.assignee.avatarUrls.16x16", "issues.fields.assignee.avatarUrls.32x32"}),
    #"Expanded issues.fields.votes" = Table.ExpandRecordColumn(#"Expanded issues.fields.assignee.avatarUrls", "issues.fields.votes", {"self", "votes", "hasVoted"}, {"issues.fields.votes.self", "issues.fields.votes.votes", "issues.fields.votes.hasVoted"}),
    #"Expanded issues.fields.issuetype" = Table.ExpandRecordColumn(#"Expanded issues.fields.votes", "issues.fields.issuetype", {"self", "id", "description", "iconUrl", "name", "subtask", "avatarId"}, {"issues.fields.issuetype.self", "issues.fields.issuetype.id", "issues.fields.issuetype.description", "issues.fields.issuetype.iconUrl", "issues.fields.issuetype.name", "issues.fields.issuetype.subtask", "issues.fields.issuetype.avatarId"}),
    #"Expanded issues.fields.customfield_50597" = Table.ExpandRecordColumn(#"Expanded issues.fields.issuetype", "issues.fields.customfield_50597", {"self", "value", "id", "disabled"}, {"issues.fields.customfield_50597.self", "issues.fields.customfield_50597.value", "issues.fields.customfield_50597.id", "issues.fields.customfield_50597.disabled"}),
    #"Expanded issues.fields.customfield_50598" = Table.ExpandRecordColumn(#"Expanded issues.fields.customfield_50597", "issues.fields.customfield_50598", {"self", "value", "id", "disabled"}, {"issues.fields.customfield_50598.self", "issues.fields.customfield_50598.value", "issues.fields.customfield_50598.id", "issues.fields.customfield_50598.disabled"}),
    #"Expanded issues.fields.customfield_50599" = Table.ExpandRecordColumn(#"Expanded issues.fields.customfield_50598", "issues.fields.customfield_50599", {"self", "value", "id", "disabled"}, {"issues.fields.customfield_50599.self", "issues.fields.customfield_50599.value", "issues.fields.customfield_50599.id", "issues.fields.customfield_50599.disabled"}),
    #"Expanded issues.fields.customfield_26391" = Table.ExpandRecordColumn(#"Expanded issues.fields.customfield_50599", "issues.fields.customfield_26391", {"self", "value", "id", "disabled"}, {"issues.fields.customfield_26391.self", "issues.fields.customfield_26391.value", "issues.fields.customfield_26391.id", "issues.fields.customfield_26391.disabled"}),
    #"Expanded issues.fields.status" = Table.ExpandRecordColumn(#"Expanded issues.fields.customfield_26391", "issues.fields.status", {"self", "description", "iconUrl", "name", "id", "statusCategory"}, {"issues.fields.status.self", "issues.fields.status.description", "issues.fields.status.iconUrl", "issues.fields.status.name", "issues.fields.status.id", "issues.fields.status.statusCategory"}),
    #"Expanded issues.fields.status.statusCategory" = Table.ExpandRecordColumn(#"Expanded issues.fields.status", "issues.fields.status.statusCategory", {"self", "id", "key", "colorName", "name"}, {"issues.fields.status.statusCategory.self", "issues.fields.status.statusCategory.id", "issues.fields.status.statusCategory.key", "issues.fields.status.statusCategory.colorName", "issues.fields.status.statusCategory.name"}),
    #"Expanded issues.fields.creator" = Table.ExpandRecordColumn(#"Expanded issues.fields.status.statusCategory", "issues.fields.creator", {"self", "name", "key", "emailAddress", "avatarUrls", "displayName", "active", "timeZone"}, {"issues.fields.creator.self", "issues.fields.creator.name", "issues.fields.creator.key", "issues.fields.creator.emailAddress", "issues.fields.creator.avatarUrls", "issues.fields.creator.displayName", "issues.fields.creator.active", "issues.fields.creator.timeZone"}),
    #"Expanded issues.fields.creator.avatarUrls" = Table.ExpandRecordColumn(#"Expanded issues.fields.creator", "issues.fields.creator.avatarUrls", {"48x48", "24x24", "16x16", "32x32"}, {"issues.fields.creator.avatarUrls.48x48", "issues.fields.creator.avatarUrls.24x24", "issues.fields.creator.avatarUrls.16x16", "issues.fields.creator.avatarUrls.32x32"}),
    #"Expanded issues.fields.customfield_29690" = Table.ExpandRecordColumn(#"Expanded issues.fields.creator.avatarUrls", "issues.fields.customfield_29690", {"self", "value", "id", "disabled"}, {"issues.fields.customfield_29690.self", "issues.fields.customfield_29690.value", "issues.fields.customfield_29690.id", "issues.fields.customfield_29690.disabled"}),
    #"Expanded issues.fields.customfield_29594" = Table.ExpandRecordColumn(#"Expanded issues.fields.customfield_29690", "issues.fields.customfield_29594", {"steps"}, {"issues.fields.customfield_29594.steps"}),
    #"Expanded issues.fields.customfield_51393" = Table.ExpandRecordColumn(#"Expanded issues.fields.customfield_29594", "issues.fields.customfield_51393", {"self", "value", "id", "disabled"}, {"issues.fields.customfield_51393.self", "issues.fields.customfield_51393.value", "issues.fields.customfield_51393.id", "issues.fields.customfield_51393.disabled"}),
    #"Expanded issues.fields.customfield_51392" = Table.ExpandRecordColumn(#"Expanded issues.fields.customfield_51393", "issues.fields.customfield_51392", {"self", "value", "id", "disabled"}, {"issues.fields.customfield_51392.self", "issues.fields.customfield_51392.value", "issues.fields.customfield_51392.id", "issues.fields.customfield_51392.disabled"}),
    #"Split Column" = Table.SplitColumn(#"Expanded issues.fields.customfield_51392", "issues.fields.labels", each _, {"issues.fields.labels.0", "issues.fields.labels.1", "issues.fields.labels.2"}),
    #"Expanded issues.fields.reporter" = Table.ExpandRecordColumn(#"Split Column", "issues.fields.reporter", {"self", "name", "key", "emailAddress", "avatarUrls", "displayName", "active", "timeZone"}, {"issues.fields.reporter.self", "issues.fields.reporter.name", "issues.fields.reporter.key", "issues.fields.reporter.emailAddress", "issues.fields.reporter.avatarUrls", "issues.fields.reporter.displayName", "issues.fields.reporter.active", "issues.fields.reporter.timeZone"}),
    #"Expanded issues.fields.reporter.avatarUrls" = Table.ExpandRecordColumn(#"Expanded issues.fields.reporter", "issues.fields.reporter.avatarUrls", {"48x48", "24x24", "16x16", "32x32"}, {"issues.fields.reporter.avatarUrls.48x48", "issues.fields.reporter.avatarUrls.24x24", "issues.fields.reporter.avatarUrls.16x16", "issues.fields.reporter.avatarUrls.32x32"}),
    #"Expanded issues.fields.progress" = Table.ExpandRecordColumn(#"Expanded issues.fields.reporter.avatarUrls", "issues.fields.progress", {"progress", "total"}, {"issues.fields.progress.progress", "issues.fields.progress.total"}),
    #"Expanded issues.fields.customfield_29609" = Table.ExpandRecordColumn(#"Expanded issues.fields.progress", "issues.fields.customfield_29609", {"count", "statuses"}, {"issues.fields.customfield_29609.count", "issues.fields.customfield_29609.statuses"}),
    #"Expanded issues.fields.project" = Table.ExpandRecordColumn(#"Expanded issues.fields.customfield_29609", "issues.fields.project", {"self", "id", "key", "name", "projectTypeKey", "avatarUrls", "projectCategory"}, {"issues.fields.project.self", "issues.fields.project.id", "issues.fields.project.key", "issues.fields.project.name", "issues.fields.project.projectTypeKey", "issues.fields.project.avatarUrls", "issues.fields.project.projectCategory"}),
    #"Expanded issues.fields.project.avatarUrls" = Table.ExpandRecordColumn(#"Expanded issues.fields.project", "issues.fields.project.avatarUrls", {"48x48", "24x24", "16x16", "32x32"}, {"issues.fields.project.avatarUrls.48x48", "issues.fields.project.avatarUrls.24x24", "issues.fields.project.avatarUrls.16x16", "issues.fields.project.avatarUrls.32x32"}),
    #"Expanded issues.fields.project.projectCategory" = Table.ExpandRecordColumn(#"Expanded issues.fields.project.avatarUrls", "issues.fields.project.projectCategory", {"self", "id", "description", "name"}, {"issues.fields.project.projectCategory.self", "issues.fields.project.projectCategory.id", "issues.fields.project.projectCategory.description", "issues.fields.project.projectCategory.name"}),
    #"Expanded issues.fields.customfield_51414" = Table.ExpandRecordColumn(#"Expanded issues.fields.project.projectCategory", "issues.fields.customfield_51414", {"self", "value", "id", "disabled"}, {"issues.fields.customfield_51414.self", "issues.fields.customfield_51414.value", "issues.fields.customfield_51414.id", "issues.fields.customfield_51414.disabled"}),
    #"Expanded issues.fields.customfield_51413" = Table.ExpandRecordColumn(#"Expanded issues.fields.customfield_51414", "issues.fields.customfield_51413", {"self", "value", "id", "disabled"}, {"issues.fields.customfield_51413.self", "issues.fields.customfield_51413.value", "issues.fields.customfield_51413.id", "issues.fields.customfield_51413.disabled"}),
    #"Expanded issues.fields.watches" = Table.ExpandRecordColumn(#"Expanded issues.fields.customfield_51413", "issues.fields.watches", {"self", "watchCount", "isWatching"}, {"issues.fields.watches.self", "issues.fields.watches.watchCount", "issues.fields.watches.isWatching"}),
    #"Split Column1" = Table.SplitColumn(#"Expanded issues.fields.watches", "issues.fields.customfield_50592", each _, {"issues.fields.customfield_50592.0"}),
    #"Expanded issues.fields.customfield_50593" = Table.ExpandRecordColumn(#"Split Column1", "issues.fields.customfield_50593", {"self", "value", "id", "disabled"}, {"issues.fields.customfield_50593.self", "issues.fields.customfield_50593.value", "issues.fields.customfield_50593.id", "issues.fields.customfield_50593.disabled"}),
    #"Expanded issues.fields.priority" = Table.ExpandRecordColumn(#"Expanded issues.fields.customfield_50593", "issues.fields.priority", {"self", "iconUrl", "name", "id"}, {"issues.fields.priority.self", "issues.fields.priority.iconUrl", "issues.fields.priority.name", "issues.fields.priority.id"}),
    #"Expanded issues.fields.customfield_42190" = Table.ExpandRecordColumn(#"Expanded issues.fields.priority", "issues.fields.customfield_42190", {"self", "value", "id", "disabled"}, {"issues.fields.customfield_42190.self", "issues.fields.customfield_42190.value", "issues.fields.customfield_42190.id", "issues.fields.customfield_42190.disabled"}),
    #"Expanded issues.fields.aggregateprogress" = Table.ExpandRecordColumn(#"Expanded issues.fields.customfield_42190", "issues.fields.aggregateprogress", {"progress", "total"}, {"issues.fields.aggregateprogress.progress", "issues.fields.aggregateprogress.total"}),
    #"Expanded issues.fields.customfield_51836" = Table.ExpandRecordColumn(#"Expanded issues.fields.aggregateprogress", "issues.fields.customfield_51836", {"self", "value", "id", "disabled"}, {"issues.fields.customfield_51836.self", "issues.fields.customfield_51836.value", "issues.fields.customfield_51836.id", "issues.fields.customfield_51836.disabled"}),
    #"Expanded issues.fields.customfield_51835" = Table.ExpandRecordColumn(#"Expanded issues.fields.customfield_51836", "issues.fields.customfield_51835", {"self", "value", "id", "disabled"}, {"issues.fields.customfield_51835.self", "issues.fields.customfield_51835.value", "issues.fields.customfield_51835.id", "issues.fields.customfield_51835.disabled"}),
    #"Expanded issues.fields.customfield_51830" = Table.ExpandRecordColumn(#"Expanded issues.fields.customfield_51835", "issues.fields.customfield_51830", {"self", "value", "id", "disabled"}, {"issues.fields.customfield_51830.self", "issues.fields.customfield_51830.value", "issues.fields.customfield_51830.id", "issues.fields.customfield_51830.disabled"}),
    #"Expanded issues.fields.customfield_51832" = Table.ExpandRecordColumn(#"Expanded issues.fields.customfield_51830", "issues.fields.customfield_51832", {"self", "value", "id", "disabled"}, {"issues.fields.customfield_51832.self", "issues.fields.customfield_51832.value", "issues.fields.customfield_51832.id", "issues.fields.customfield_51832.disabled"}),
    #"Expanded issues.fields.customfield_51831" = Table.ExpandRecordColumn(#"Expanded issues.fields.customfield_51832", "issues.fields.customfield_51831", {"self", "value", "id", "disabled"}, {"issues.fields.customfield_51831.self", "issues.fields.customfield_51831.value", "issues.fields.customfield_51831.id", "issues.fields.customfield_51831.disabled"}),
    #"Expanded issues.fields.customfield_51834" = Table.ExpandRecordColumn(#"Expanded issues.fields.customfield_51831", "issues.fields.customfield_51834", {"self", "value", "id", "disabled"}, {"issues.fields.customfield_51834.self", "issues.fields.customfield_51834.value", "issues.fields.customfield_51834.id", "issues.fields.customfield_51834.disabled"}),
    #"Expanded issues.fields.customfield_51833" = Table.ExpandRecordColumn(#"Expanded issues.fields.customfield_51834", "issues.fields.customfield_51833", {"self", "value", "id", "disabled"}, {"issues.fields.customfield_51833.self", "issues.fields.customfield_51833.value", "issues.fields.customfield_51833.id", "issues.fields.customfield_51833.disabled"}),
    #"Expanded issues.fields.customfield_51825" = Table.ExpandRecordColumn(#"Expanded issues.fields.customfield_51833", "issues.fields.customfield_51825", {"self", "value", "id", "disabled"}, {"issues.fields.customfield_51825.self", "issues.fields.customfield_51825.value", "issues.fields.customfield_51825.id", "issues.fields.customfield_51825.disabled"}),
    #"Expanded issues.fields.customfield_50615" = Table.ExpandRecordColumn(#"Expanded issues.fields.customfield_51825", "issues.fields.customfield_50615", {"self", "value", "id", "disabled"}, {"issues.fields.customfield_50615.self", "issues.fields.customfield_50615.value", "issues.fields.customfield_50615.id", "issues.fields.customfield_50615.disabled"}),
    #"Expanded issues.fields.customfield_51824" = Table.ExpandRecordColumn(#"Expanded issues.fields.customfield_50615", "issues.fields.customfield_51824", {"self", "value", "id", "disabled"}, {"issues.fields.customfield_51824.self", "issues.fields.customfield_51824.value", "issues.fields.customfield_51824.id", "issues.fields.customfield_51824.disabled"}),
    #"Expanded issues.fields.customfield_51827" = Table.ExpandRecordColumn(#"Expanded issues.fields.customfield_51824", "issues.fields.customfield_51827", {"self", "value", "id", "disabled"}, {"issues.fields.customfield_51827.self", "issues.fields.customfield_51827.value", "issues.fields.customfield_51827.id", "issues.fields.customfield_51827.disabled"}),
    #"Expanded issues.fields.customfield_51826" = Table.ExpandRecordColumn(#"Expanded issues.fields.customfield_51827", "issues.fields.customfield_51826", {"self", "value", "id", "disabled", "child"}, {"issues.fields.customfield_51826.self", "issues.fields.customfield_51826.value", "issues.fields.customfield_51826.id", "issues.fields.customfield_51826.disabled", "issues.fields.customfield_51826.child"}),
    #"Expanded issues.fields.customfield_51826.child" = Table.ExpandRecordColumn(#"Expanded issues.fields.customfield_51826", "issues.fields.customfield_51826.child", {"self", "value", "id", "disabled"}, {"issues.fields.customfield_51826.child.self", "issues.fields.customfield_51826.child.value", "issues.fields.customfield_51826.child.id", "issues.fields.customfield_51826.child.disabled"}),
    #"Expanded issues.fields.customfield_51829" = Table.ExpandRecordColumn(#"Expanded issues.fields.customfield_51826.child", "issues.fields.customfield_51829", {"self", "value", "id", "disabled"}, {"issues.fields.customfield_51829.self", "issues.fields.customfield_51829.value", "issues.fields.customfield_51829.id", "issues.fields.customfield_51829.disabled"}),
    #"Expanded issues.fields.customfield_51828" = Table.ExpandRecordColumn(#"Expanded issues.fields.customfield_51829", "issues.fields.customfield_51828", {"self", "value", "id", "disabled"}, {"issues.fields.customfield_51828.self", "issues.fields.customfield_51828.value", "issues.fields.customfield_51828.id", "issues.fields.customfield_51828.disabled"}),
    #"Expanded issues.fields.customfield_50610" = Table.ExpandRecordColumn(#"Expanded issues.fields.customfield_51828", "issues.fields.customfield_50610", {"self", "value", "id", "disabled"}, {"issues.fields.customfield_50610.self", "issues.fields.customfield_50610.value", "issues.fields.customfield_50610.id", "issues.fields.customfield_50610.disabled"}),
    #"Expanded issues.fields.customfield_51821" = Table.ExpandRecordColumn(#"Expanded issues.fields.customfield_50610", "issues.fields.customfield_51821", {"self", "value", "id", "disabled"}, {"issues.fields.customfield_51821.self", "issues.fields.customfield_51821.value", "issues.fields.customfield_51821.id", "issues.fields.customfield_51821.disabled"}),
    #"Expanded issues.fields.customfield_50611" = Table.ExpandRecordColumn(#"Expanded issues.fields.customfield_51821", "issues.fields.customfield_50611", {"self", "value", "id", "disabled"}, {"issues.fields.customfield_50611.self", "issues.fields.customfield_50611.value", "issues.fields.customfield_50611.id", "issues.fields.customfield_50611.disabled"}),
    #"Expanded issues.fields.customfield_50612" = Table.ExpandRecordColumn(#"Expanded issues.fields.customfield_50611", "issues.fields.customfield_50612", {"self", "value", "id", "disabled"}, {"issues.fields.customfield_50612.self", "issues.fields.customfield_50612.value", "issues.fields.customfield_50612.id", "issues.fields.customfield_50612.disabled"}),
    #"Expanded issues.fields.customfield_50613" = Table.ExpandRecordColumn(#"Expanded issues.fields.customfield_50612", "issues.fields.customfield_50613", {"self", "value", "id", "disabled"}, {"issues.fields.customfield_50613.self", "issues.fields.customfield_50613.value", "issues.fields.customfield_50613.id", "issues.fields.customfield_50613.disabled"}),
    #"Removed Other Columns" = Table.SelectColumns(#"Expanded issues.fields.customfield_50613",{"maxResults", "total", "issues.key", "issues.fields.assignee.name", "issues.fields.assignee.emailAddress", "issues.fields.assignee.displayName", "issues.fields.duedate", "issues.fields.status.name", "issues.fields.creator.name", "issues.fields.creator.emailAddress", "issues.fields.creator.displayName", "issues.fields.reporter.name", "issues.fields.reporter.emailAddress", "issues.fields.reporter.displayName", "issues.fields.resolutiondate", "issues.fields.updated", "issues.fields.summary", "issues.fields.created"}),
    #"Renamed Columns" = Table.RenameColumns(#"Removed Other Columns",{{"issues.fields.created", "Created_Time"}, {"issues.fields.summary", "Issue Summary"}, {"issues.fields.updated", "Last Update Time"}, {"issues.fields.resolutiondate", "Resolution Time"}, {"issues.fields.reporter.displayName", "Reporter Name"}, {"issues.fields.reporter.emailAddress", "Reporter Email Address"}, {"issues.fields.reporter.name", "Reporter ID"}, {"issues.fields.creator.displayName", "Creator Name"}, {"issues.fields.creator.emailAddress", "Creator Email ID"}, {"issues.fields.creator.name", "Creator ID"}, {"issues.fields.status.name", "Issue Status"}, {"issues.fields.duedate", "Issue Due Date"}, {"issues.fields.assignee.displayName", "Assignee Name"}, {"issues.fields.assignee.emailAddress", "Assignee Email ID"}, {"issues.fields.assignee.name", "Assignee ID"}, {"issues.key", "Issue ID"}})
in
    #"Renamed Columns"